# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20130707014720) do

  create_table "atbats", force: true do |t|
    t.integer  "num"
    t.integer  "b"
    t.integer  "s"
    t.integer  "o"
    t.integer  "start_tfs"
    t.string   "start_tfs_zulu"
    t.integer  "batter_id"
    t.integer  "pitcher_id"
    t.string   "stand"
    t.string   "b_height"
    t.string   "p_throws"
    t.string   "des"
    t.string   "event"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "game_id"
    t.text     "game_id_num",    limit: 255
    t.string   "pitcher_name"
    t.string   "batter_name"
    t.string   "batter_team"
    t.string   "pitcher_team"
  end

  create_table "batter_details", force: true do |t|
    t.string   "p_id_ty"
    t.integer  "p_id"
    t.string   "pitch_type"
    t.string   "ab"
    t.float    "avg"
    t.integer  "hr"
    t.integer  "rbi"
    t.integer  "bb"
    t.integer  "so"
    t.float    "ops"
    t.string   "rating"
    t.string   "sweetness"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "p_b"
  end

  create_table "batters", force: true do |t|
    t.integer  "p_id"
    t.string   "name"
    t.string   "active_sw"
    t.string   "status_cd"
    t.string   "last_name"
    t.string   "name_display_last_first"
    t.string   "name_display_first_last"
    t.string   "name_display_roster"
    t.string   "bats"
    t.string   "throws"
    t.string   "pos"
    t.integer  "jersey_number"
    t.integer  "year"
    t.integer  "team_id"
    t.string   "team_abbrev"
    t.integer  "league_id"
    t.string   "league"
    t.integer  "league_games"
    t.integer  "h"
    t.integer  "ab"
    t.integer  "tb"
    t.float    "avg"
    t.float    "avg_sort"
    t.float    "slg"
    t.float    "slg_sort"
    t.integer  "a"
    t.integer  "e"
    t.integer  "po"
    t.integer  "g"
    t.integer  "r"
    t.integer  "b2"
    t.integer  "b3"
    t.integer  "hr"
    t.integer  "rbi"
    t.integer  "sac"
    t.integer  "sf"
    t.integer  "hbp"
    t.integer  "bb"
    t.integer  "ibb"
    t.integer  "so"
    t.integer  "sb"
    t.integer  "cs"
    t.integer  "gidp"
    t.float    "ops"
    t.float    "ops_sort"
    t.float    "obp"
    t.float    "obp_sort"
    t.integer  "np"
    t.integer  "go"
    t.integer  "ao"
    t.integer  "tpa"
    t.integer  "of_a"
    t.integer  "ph_ab"
    t.integer  "ph_h"
    t.integer  "ph_hr"
    t.integer  "ph_rbi"
    t.integer  "last10_ab"
    t.integer  "last10_h"
    t.integer  "last10_hr"
    t.integer  "last10_rbi"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "height"
    t.string   "weight"
    t.string   "dob"
    t.float    "career_avg"
    t.integer  "career_ab"
    t.integer  "career_h"
    t.integer  "career_bb"
    t.integer  "career_so"
    t.integer  "career_r"
    t.integer  "career_sb"
    t.integer  "career_hr"
    t.integer  "career_rbi"
    t.float    "empty_avg"
    t.integer  "empty_ab"
    t.integer  "empty_h"
    t.integer  "empty_bb"
    t.integer  "empty_so"
    t.integer  "empty_r"
    t.integer  "empty_sb"
    t.integer  "empty_hr"
    t.integer  "empty_rbi"
    t.float    "month_avg"
    t.integer  "month_ab"
    t.integer  "month_h"
    t.integer  "month_bb"
    t.integer  "month_so"
    t.integer  "month_r"
    t.integer  "month_sb"
    t.integer  "month_hr"
    t.integer  "month_rbi"
    t.float    "risp_avg"
    t.integer  "risp_ab"
    t.integer  "risp_h"
    t.integer  "risp_bb"
    t.integer  "risp_so"
    t.integer  "risp_r"
    t.integer  "risp_sb"
    t.integer  "risp_hr"
    t.integer  "risp_rbi"
    t.float    "men_on_avg"
    t.integer  "men_on_ab"
    t.integer  "men_on_h"
    t.integer  "men_on_bb"
    t.integer  "men_on_so"
    t.integer  "men_on_r"
    t.integer  "men_on_sb"
    t.integer  "men_on_hr"
    t.integer  "men_on_rbi"
    t.float    "loaded_avg"
    t.integer  "loaded_ab"
    t.integer  "loaded_h"
    t.integer  "loaded_bb"
    t.integer  "loaded_so"
    t.integer  "loaded_r"
    t.integer  "loaded_sb"
    t.integer  "loaded_hr"
    t.integer  "loaded_rbi"
    t.float    "vs_lhp_avg"
    t.integer  "vs_lhp_ab"
    t.integer  "vs_lhp_h"
    t.integer  "vs_lhp_bb"
    t.integer  "vs_lhp_so"
    t.integer  "vs_lhp_r"
    t.integer  "vs_lhp_sb"
    t.integer  "vs_lhp_hr"
    t.integer  "vs_lhp_rbi"
    t.float    "vs_rhp_avg"
    t.integer  "vs_rhp_ab"
    t.integer  "vs_rhp_h"
    t.integer  "vs_rhp_bb"
    t.integer  "vs_rhp_so"
    t.integer  "vs_rhp_r"
    t.integer  "vs_rhp_sb"
    t.integer  "vs_rhp_hr"
    t.integer  "vs_rhp_rbi"
    t.string   "month_des"
    t.float    "career_ops"
    t.float    "month_ops"
    t.float    "empty_ops"
    t.float    "men_on_ops"
    t.float    "risp_ops"
    t.float    "loaded_ops"
    t.float    "vs_lhp_ops"
    t.float    "vs_rhp_ops"
  end

  create_table "data", force: true do |t|
    t.string   "gid"
    t.integer  "year"
    t.integer  "month"
    t.integer  "day"
    t.string   "team_name"
    t.integer  "team_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "data_fetchers", force: true do |t|
    t.string   "gid"
    t.string   "team_name"
    t.integer  "team_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "examples", force: true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "pitch_tendencies", force: true do |t|
    t.integer  "p_id"
    t.string   "game_id"
    t.integer  "game_num"
    t.float    "game_vel"
    t.string   "pitch_type"
    t.integer  "num"
    t.float    "movement"
    t.float    "pfx"
    t.float    "vel"
    t.float    "avg_x0"
    t.float    "avg_z0"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "pitch_type_details", force: true do |t|
    t.string   "p_b"
    t.string   "p_id_ty"
    t.integer  "p_id"
    t.string   "pitch_type"
    t.integer  "ab",         limit: 255
    t.float    "avg"
    t.integer  "hr"
    t.integer  "rbi"
    t.integer  "bb"
    t.integer  "so"
    t.float    "ops"
    t.string   "rating"
    t.string   "sweetness"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "pitchers", force: true do |t|
    t.integer  "p_id"
    t.string   "name"
    t.string   "active_sw"
    t.string   "status_cd"
    t.string   "last_name"
    t.string   "name_display_last_first"
    t.string   "name_display_first_last"
    t.string   "name_display_roster"
    t.string   "bats"
    t.string   "throws"
    t.string   "pos"
    t.integer  "jersey_number"
    t.integer  "year"
    t.integer  "team_id"
    t.string   "team_abbrev"
    t.integer  "league_id"
    t.string   "league"
    t.integer  "league_games"
    t.integer  "ip"
    t.float    "ip_sort"
    t.integer  "er"
    t.float    "era"
    t.float    "era_sort"
    t.integer  "h"
    t.integer  "r"
    t.integer  "hr"
    t.integer  "hb"
    t.integer  "bb"
    t.integer  "ibb"
    t.integer  "so"
    t.integer  "wp"
    t.float    "avg"
    t.float    "avg_sort"
    t.float    "slg"
    t.float    "slg_sort"
    t.float    "whip"
    t.float    "whip_sort"
    t.float    "pct"
    t.float    "pct_sort"
    t.integer  "ab"
    t.integer  "sf"
    t.integer  "sac"
    t.integer  "gidp"
    t.integer  "p_inh_runner"
    t.integer  "p_inh_runner_scored"
    t.integer  "ao"
    t.integer  "go"
    t.integer  "np"
    t.integer  "bk"
    t.integer  "hld"
    t.integer  "tpa"
    t.integer  "po"
    t.integer  "a"
    t.integer  "e"
    t.integer  "g"
    t.integer  "gs"
    t.integer  "w"
    t.integer  "l"
    t.integer  "cg"
    t.integer  "gf"
    t.integer  "sho"
    t.integer  "sv"
    t.integer  "bsv"
    t.integer  "svo"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "height"
    t.string   "weight"
    t.string   "dob"
    t.float    "career_avg"
    t.integer  "career_ab"
    t.integer  "career_h"
    t.integer  "career_bb"
    t.integer  "career_so"
    t.integer  "career_hr"
    t.integer  "career_rbi"
    t.integer  "career_w"
    t.integer  "career_l"
    t.integer  "career_sv"
    t.float    "career_ip"
    t.float    "career_whip"
    t.float    "career_era"
    t.float    "empty_avg"
    t.integer  "empty_ab"
    t.integer  "empty_h"
    t.integer  "empty_bb"
    t.integer  "empty_so"
    t.integer  "empty_sb"
    t.integer  "empty_hr"
    t.integer  "empty_rbi"
    t.integer  "empty_w"
    t.integer  "empty_l"
    t.integer  "empty_sv"
    t.float    "empty_ip"
    t.float    "empty_whip"
    t.float    "empty_era"
    t.string   "month_des"
    t.float    "month_avg"
    t.integer  "month_ab"
    t.integer  "month_h"
    t.integer  "month_bb"
    t.integer  "month_so"
    t.integer  "month_sb"
    t.integer  "month_hr"
    t.integer  "month_rbi"
    t.integer  "month_w"
    t.integer  "month_l"
    t.integer  "month_sv"
    t.float    "month_ip"
    t.float    "month_whip"
    t.float    "month_era"
    t.float    "risp_avg"
    t.integer  "risp_ab"
    t.integer  "risp_h"
    t.integer  "risp_bb"
    t.integer  "risp_so"
    t.integer  "risp_sb"
    t.integer  "risp_hr"
    t.integer  "risp_rbi"
    t.integer  "risp_w"
    t.integer  "risp_l"
    t.integer  "risp_sv"
    t.float    "risp_ip"
    t.float    "risp_whip"
    t.float    "risp_era"
    t.float    "men_on_avg"
    t.integer  "men_on_ab"
    t.integer  "men_on_h"
    t.integer  "men_on_bb"
    t.integer  "men_on_so"
    t.integer  "men_on_sb"
    t.integer  "men_on_hr"
    t.integer  "men_on_rbi"
    t.integer  "men_on_w"
    t.integer  "men_on_l"
    t.integer  "men_on_sv"
    t.float    "men_on_ip"
    t.float    "men_on_whip"
    t.float    "men_on_era"
    t.float    "loaded_avg"
    t.integer  "loaded_ab"
    t.integer  "loaded_h"
    t.integer  "loaded_bb"
    t.integer  "loaded_so"
    t.integer  "loaded_sb"
    t.integer  "loaded_hr"
    t.integer  "loaded_rbi"
    t.integer  "loaded_w"
    t.integer  "loaded_l"
    t.integer  "loaded_sv"
    t.float    "loaded_ip"
    t.float    "loaded_whip"
    t.float    "loaded_era"
    t.float    "vs_lhb_avg"
    t.integer  "vs_lhb_ab"
    t.integer  "vs_lhb_h"
    t.integer  "vs_lhb_bb"
    t.integer  "vs_lhb_so"
    t.integer  "vs_lhb_sb"
    t.integer  "vs_lhb_hr"
    t.integer  "vs_lhb_rbi"
    t.integer  "vs_lhb_w"
    t.integer  "vs_lhb_l"
    t.integer  "vs_lhb_sv"
    t.float    "vs_lhb_ip"
    t.float    "vs_lhb_whip"
    t.float    "vs_lhb_era"
    t.float    "vs_rhb_avg"
    t.integer  "vs_rhb_ab"
    t.integer  "vs_rhb_h"
    t.integer  "vs_rhb_bb"
    t.integer  "vs_rhb_so"
    t.integer  "vs_rhb_sb"
    t.integer  "vs_rhb_hr"
    t.integer  "vs_rhb_rbi"
    t.integer  "vs_rhb_w"
    t.integer  "vs_rhb_l"
    t.integer  "vs_rhb_sv"
    t.float    "vs_rhb_ip"
    t.float    "vs_rhb_whip"
    t.float    "vs_rhb_era"
  end

# Could not dump table "pitchings" because of following NoMethodError
#   undefined method `[]' for nil:NilClass

  create_table "players", force: true do |t|
    t.integer  "p_id"
    t.string   "name"
    t.string   "bats"
    t.string   "throws"
    t.string   "pos"
    t.integer  "jersey_number"
    t.integer  "team_id"
    t.integer  "league_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "game"
  end

  create_table "teams", force: true do |t|
    t.string   "team_name"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "team_abbrev"
    t.integer  "tb_h"
    t.integer  "tb_ab"
    t.integer  "tb_tb"
    t.float    "tb_avg"
    t.float    "tb_slg"
    t.integer  "tb_g"
    t.integer  "tb_r"
    t.integer  "tb_b2"
    t.integer  "tb_b3"
    t.integer  "tb_hr"
    t.integer  "tb_rbi"
    t.integer  "tb_sac"
    t.integer  "tb_sf"
    t.integer  "tb_hbp"
    t.integer  "tb_bb"
    t.integer  "tb_ibb"
    t.integer  "tb_so"
    t.integer  "tb_sb"
    t.integer  "tb_cs"
    t.integer  "tb_gidp"
    t.float    "tb_obp"
    t.float    "tb_ops"
    t.integer  "tp_ip"
    t.integer  "tp_er"
    t.float    "tp_era"
    t.float    "tp_whip"
    t.integer  "tp_h"
    t.integer  "tp_r"
    t.integer  "tp_hr"
    t.integer  "tp_hb"
    t.integer  "tp_bb"
    t.integer  "tp_ibb"
    t.integer  "tp_so"
    t.integer  "tp_wp"
    t.integer  "tp_g"
    t.integer  "tp_gs"
    t.integer  "tp_w"
    t.integer  "tp_l"
    t.integer  "tp_cg"
    t.integer  "tp_gf"
    t.integer  "tp_sho"
    t.integer  "tp_sv"
    t.integer  "tp_bsv"
    t.integer  "tp_svo"
    t.integer  "team_id"
    t.integer  "league_id"
    t.string   "game_id"
    t.float    "win_pct"
  end

end
