class AddColumnsToBatters < ActiveRecord::Migration
  def change
    add_column :batters, :height, :string
    add_column :batters, :weight, :string
    add_column :batters, :dob, :string
    add_column :batters, :carrer_avg, :float
    add_column :batters, :carrer_ab, :integer
    add_column :batters, :carrer_h, :integer
    add_column :batters, :carrer_bb, :integer
    add_column :batters, :carrer_so, :integer
    add_column :batters, :carrer_r, :integer
    add_column :batters, :carrer_sb, :integer
    add_column :batters, :carrer_hr, :integer
    add_column :batters, :carrer_rbi, :integer
    add_column :batters, :empty_avg, :float
    add_column :batters, :empty_ab, :integer
    add_column :batters, :empty_h, :integer
    add_column :batters, :empty_bb, :integer
    add_column :batters, :empty_so, :integer
    add_column :batters, :empty_r, :integer
    add_column :batters, :empty_sb, :integer
    add_column :batters, :empty_hr, :integer
    add_column :batters, :empty_rbi, :integer
    add_column :batters, :month_avg, :float
    add_column :batters, :month_ab, :integer
    add_column :batters, :month_h, :integer
    add_column :batters, :month_bb, :integer
    add_column :batters, :month_so, :integer
    add_column :batters, :month_r, :integer
    add_column :batters, :month_sb, :integer
    add_column :batters, :month_hr, :integer
    add_column :batters, :month_rbi, :integer
    add_column :batters, :risp_avg, :float
    add_column :batters, :risp_ab, :integer
    add_column :batters, :risp_h, :integer
    add_column :batters, :risp_bb, :integer
    add_column :batters, :risp_so, :integer
    add_column :batters, :risp_r, :integer
    add_column :batters, :risp_sb, :integer
    add_column :batters, :risp_hr, :integer
    add_column :batters, :risp_rbi, :integer
    add_column :batters, :men_on_avg, :float
    add_column :batters, :men_on_ab, :integer
    add_column :batters, :men_on_h, :integer
    add_column :batters, :men_on_bb, :integer
    add_column :batters, :men_on_so, :integer
    add_column :batters, :men_on_r, :integer
    add_column :batters, :men_on_sb, :integer
    add_column :batters, :men_on_hr, :integer
    add_column :batters, :men_on_rbi, :integer
    add_column :batters, :loaded_avg, :float
    add_column :batters, :loaded_ab, :integer
    add_column :batters, :loaded_h, :integer
    add_column :batters, :loaded_bb, :integer
    add_column :batters, :loaded_so, :integer
    add_column :batters, :loaded_r, :integer
    add_column :batters, :loaded_sb, :integer
    add_column :batters, :loaded_hr, :integer
    add_column :batters, :loaded_rbi, :integer
    add_column :batters, :vs_lhp_avg, :float
    add_column :batters, :vs_lhp_ab, :integer
    add_column :batters, :vs_lhp_h, :integer
    add_column :batters, :vs_lhp_bb, :integer
    add_column :batters, :vs_lhp_so, :integer
    add_column :batters, :vs_lhp_r, :integer
    add_column :batters, :vs_lhp_sb, :integer
    add_column :batters, :vs_lhp_hr, :integer
    add_column :batters, :vs_lhp_rbi, :integer
    add_column :batters, :vs_rhp_avg, :float
    add_column :batters, :vs_rhp_ab, :integer
    add_column :batters, :vs_rhp_h, :integer
    add_column :batters, :vs_rhp_bb, :integer
    add_column :batters, :vs_rhp_so, :integer
    add_column :batters, :vs_rhp_r, :integer
    add_column :batters, :vs_rhp_sb, :integer
    add_column :batters, :vs_rhp_hr, :integer
    add_column :batters, :vs_rhp_rbi, :integer


  end
end
